CREATE TABLE us_accidents (
	"ID" TEXT PRIMARY KEY,
	"Source" TEXT,
	"TMC" NUMERIC,
	"Severity" INTEGER,
	"Start_Time" TEXT,
	"End_Time" TEXT,
	"Start_Lat" NUMERIC,
	"Start_Lng" NUMERIC,
	"End_Lat" NUMERIC,
	"End_Lng" NUMERIC,
	"Distance_mi" NUMERIC,
	"Description" TEXT,
	"Number" NUMERIC,
	"Street" TEXT,
	"Side" TEXT,
	"City" TEXT,
	"County" TEXT,
	"State" TEXT,
	"Zipcode" TEXT,
	"Country" TEXT,
	"Timezone" TEXT,
	"Airport_Code" TEXT,
	"Weather_Timestamp" TEXT,
	"Temperature_F" NUMERIC,
	"Wind_Chill_F" NUMERIC,
	"Humidity_rate" NUMERIC,
	"Pressure_in" NUMERIC,
	"Visibility_mi" NUMERIC,
	"Wind_Direction" TEXT,
	"Wind_Speed_mph" NUMERIC,
	"Precipitation_in" NUMERIC,
	"Weather_Condition" TEXT,
	"Amenity" BOOLEAN,
	"Bump" BOOLEAN,
	"Crossing" BOOLEAN,
	"Give_Way" BOOLEAN,
	"Junction" BOOLEAN,
	"No_Exit" BOOLEAN,
	"Railway" BOOLEAN,
	"Roundabout" BOOLEAN,
	"Station" BOOLEAN,
	"Stop" BOOLEAN,
	"Traffic_Calming" BOOLEAN,
	"Traffic_Signal" BOOLEAN,
	"Turning_Loop" BOOLEAN,
	"Sunrise_Sunset" TEXT,
	"Civil_Twilight" TEXT,
	"Nautical_Twilight" TEXT,
	"Astronomical_Twilight" TEXT
);

CREATE TABLE us_census (
	"State" TEXT PRIMARY KEY,
	"Total" INTEGER,
	"Male" INTEGER,
	"Female" INTEGER,
	"Age_16_19" INTEGER,
	"Age_20_24" INTEGER,
	"Age_25_44" INTEGER,
	"Age_45_54" INTEGER,
	"Age_55_59" INTEGER,
	"Age_60_" INTEGER,
	"State_Name" TEXT
);